apiVersion: v1
kind: Service
metadata:
  name: aimvoxtral4tts
  namespace: {{ .Release.Namespace }}
  labels:
    app: aimvoxtral4tts
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: dashboard
    port: {{ .Values.dashboardPort }}
    targetPort: {{ .Values.dashboardPort }}
    protocol: TCP
  - name: api
    port: {{ .Values.apiPort }}
    targetPort: {{ .Values.apiPort }}
    protocol: TCP
  selector:
    app: aimvoxtral4tts
