image:
  repository: docker.io/bayerhazard/aimighty-voxtral-tts
  tag: "1.0.4"
  pullPolicy: IfNotPresent
nginx:
  image: nginx:alpine
replicaCount: 1
revisionHistoryLimit: 1
apiPort: 8000
dashboardPort: 8080
strategy:
  type: Recreate
resources:
  limits:
    cpu: "4"
    memory: 32Gi
    nvidia.com/gpu: "1"
  requests:
    cpu: "2"
    memory: 16Gi
nginxResources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi
env:
  MODEL_DIR: /app/models/original
  FLOW_STEPS: "8"
  USE_INT4: "true"
serveArgs:
  modelDir: /app/models/original
  port: "8000"
  host: "0.0.0.0"
  flowSteps: "8"
  noCompile: "false"
userspace:
  appData: /olares/rootfs/userspace/pvc-userspace-aimighty-phbiddku99qy4cuz
volumes:
  dshm:
    sizeLimit: 2Gi
startupProbe:
  httpGet:
    path: /health
    port: 8000
  failureThreshold: 120
  periodSeconds: 10
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 600
  periodSeconds: 60
  timeoutSeconds: 15
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 3
kubeletCidrs:
  - 172.20.0.0/16
service:
  type: ClusterIP
